Project as at 18/10/2024
DanSam5K/mini-shell-project pull request #23
Opened 2024-10-18 20:53 UTC by Remi-Jacobs

Current state of project

2024-10-21 15:16 UTC, DanSam5K requested changes
### Changes required
Good job so far!
There are some issues that you still need to work on to go to the next! but you are almost there!
Cheers and Happy coding!👏👏👏

2024-10-21 15:16 UTC, DanSam5K commented on .vscode/launch.json
Kindly remove the file delete it locally and remotely.
Then add a ```.gitignore``` file and add the folder into the ```.gitignore``` file

2024-10-21 15:16 UTC, DanSam5K commented on .vscode/settings.json
same as above

2024-10-21 15:16 UTC, DanSam5K commented on .vscode/tasks.json
this also

2024-10-21 15:16 UTC, DanSam5K commented on src/builtins/cd.c
I think it would be nice to only provide only one implementation of the cd builtin. the other or alternative solution can be commented and allowed later we can delete.

2024-10-21 15:16 UTC, DanSam5K commented on src/builtins/env.c
Good Job!
- Also pick one comment the other.

2024-10-21 15:16 UTC, DanSam5K commented on src/builtins/export.c
Great work here also pick one.

2024-10-21 15:16 UTC, DanSam5K commented on src/builtins/pwd.c
great!

2024-10-21 15:16 UTC, DanSam5K commented on src/signals/signals.c
> +}
Seems you added a type struct definition?
In case you make use of it anywhere in the code kindly add it to the header file and specify the use case.

2024-10-21 21:19 UTC, Remi-Jacobs commented
Reviewed  and updated

2024-10-22 11:58 UTC, DanSam5K approved these changes
Hi @Remi-Jacobs , 
God job looks complete!  There is nothing else to say other than... it's time to merge it :shipit:

2024-10-22 11:59 UTC, merged